"use client";

import Link from "next/link";

export default function LegalPage() {
  return (
    <div className="min-h-screen bg-white text-gray-900 font-sans">
      <div className="max-w-3xl mx-auto px-6 py-16">
        {/* Header */}
        <Link href="/" className="text-sm text-blue-500 hover:text-blue-600 transition-colors">
          ← Back to EM Protocols
        </Link>

        <h1 className="text-3xl font-bold mt-6 mb-2">Legal &amp; Disclaimer</h1>
        <p className="text-sm text-gray-400 mb-10">Last updated: February 25, 2026</p>

        {/* Clinical Disclaimer */}
        <section className="mb-10">
          <h2 className="text-xl font-semibold mb-3">Clinical Disclaimer</h2>
          <p className="text-sm leading-relaxed text-gray-700 mb-3">
            EM Protocols is a clinical decision support tool designed exclusively for use by trained healthcare professionals, including emergency physicians, advanced practice providers, nurses, residents, and medical students.
          </p>
          <p className="text-sm leading-relaxed text-gray-700 mb-3">
            <strong>This tool is not a substitute for professional medical judgment.</strong> The information provided is intended as a reference aid and should not be used as the sole basis for clinical decisions. Users are responsible for independently verifying all information against institutional protocols, current medical literature, and their own clinical assessment of individual patients.
          </p>
          <p className="text-sm leading-relaxed text-gray-700">
            This tool is not intended for use by patients or the general public and does not establish a provider–patient relationship.
          </p>
        </section>

        {/* AI Disclosure */}
        <section className="mb-10">
          <h2 className="text-xl font-semibold mb-3">AI-Generated Content Disclosure</h2>
          <p className="text-sm leading-relaxed text-gray-700 mb-3">
            Answers provided by EM Protocols are generated by Google Gemini 2.0 Flash, a large language model, using Retrieval-Augmented Generation (RAG). The system retrieves relevant excerpts from indexed sources and synthesizes a response with inline citations.
          </p>
          <p className="text-sm leading-relaxed text-gray-700 mb-3">
            <strong>AI-generated responses have not been reviewed by a human and may contain errors, omissions, or inaccuracies.</strong> Content may not reflect the most current medical evidence or institutional guidelines. The AI may occasionally misinterpret source material or produce responses that appear plausible but are incorrect.
          </p>
          <p className="text-sm leading-relaxed text-gray-700">
            Users should always review cited sources directly and exercise independent clinical judgment before acting on any information provided by this tool.
          </p>
        </section>

        {/* No Warranty */}
        <section className="mb-10">
          <h2 className="text-xl font-semibold mb-3">No Warranty</h2>
          <p className="text-sm leading-relaxed text-gray-700 mb-3">
            EM Protocols and all content, services, and outputs are provided <strong>&quot;as is&quot;</strong> and <strong>&quot;as available&quot;</strong> without warranty of any kind, either express or implied, including but not limited to implied warranties of merchantability, fitness for a particular purpose, accuracy, completeness, or non-infringement.
          </p>
          <p className="text-sm leading-relaxed text-gray-700">
            The developers of EM Protocols, its contributors, and affiliated organizations do not warrant that the service will be uninterrupted, error-free, or that defects will be corrected. Use of this tool is at your own risk.
          </p>
        </section>

        {/* Limitation of Liability */}
        <section className="mb-10">
          <h2 className="text-xl font-semibold mb-3">Limitation of Liability</h2>
          <p className="text-sm leading-relaxed text-gray-700">
            In no event shall the developers, contributors, or affiliated organizations be liable for any direct, indirect, incidental, consequential, special, or exemplary damages, including but not limited to damages for personal injury, loss of data, or other intangible losses, arising out of or in connection with the use of or inability to use this tool, even if advised of the possibility of such damages. The clinician end user is solely responsible for all decisions regarding medical diagnosis and treatment for any person under their care.
          </p>
        </section>

        {/* Data Sources & Attribution */}
        <section className="mb-10">
          <h2 className="text-xl font-semibold mb-3">Data Sources &amp; Attribution</h2>
          <p className="text-sm leading-relaxed text-gray-700 mb-4">
            EM Protocols retrieves information from the following sources. All content is stored in a search index and served as cited excerpts with attribution — it is not used to train AI models.
          </p>

          <div className="space-y-4">
            <div className="border border-gray-200 rounded-lg p-4">
              <h3 className="text-sm font-semibold">Local Institutional Protocols</h3>
              <p className="text-xs text-gray-500 mt-1">Proprietary — uploaded by authorized institutional administrators. Department-specific clinical protocols, pathways, and guidelines.</p>
            </div>

            <div className="border border-gray-200 rounded-lg p-4">
              <h3 className="text-sm font-semibold">WikEM</h3>
              <p className="text-xs text-gray-500 mt-1">
                Content from <a href="https://wikem.org" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">wikem.org</a>, the &ldquo;Wikipedia of Emergency Medicine,&rdquo; licensed under{" "}
                <a href="https://creativecommons.org/licenses/by-sa/3.0/" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">CC BY-SA 3.0</a>.
                A project of the OpenEM Foundation.
              </p>
            </div>

            <div className="border border-gray-200 rounded-lg p-4">
              <h3 className="text-sm font-semibold">PMC Open Access</h3>
              <p className="text-xs text-gray-500 mt-1">
                Full-text peer-reviewed emergency medicine articles from{" "}
                <a href="https://www.ncbi.nlm.nih.gov/pmc/" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">PubMed Central</a>{" "}
                Open Access Subset. Individual articles carry their own Creative Commons or public domain licenses. Journals include Annals of Emergency Medicine, Academic Emergency Medicine, Western Journal of Emergency Medicine, and others.
              </p>
            </div>

            <div className="border border-gray-200 rounded-lg p-4">
              <h3 className="text-sm font-semibold">LITFL (Life in the Fast Lane)</h3>
              <p className="text-xs text-gray-500 mt-1">
                Content from <a href="https://litfl.com" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">litfl.com</a>, licensed under{" "}
                <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">CC BY-NC-SA 4.0</a>.
                Emergency medicine, critical care, toxicology, and ECG education.
              </p>
            </div>

            <div className="border border-gray-200 rounded-lg p-4">
              <h3 className="text-sm font-semibold">REBEL EM</h3>
              <p className="text-xs text-gray-500 mt-1">
                Content from <a href="https://rebelem.com" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">rebelem.com</a> by Salim Rezaie, MD, licensed under{" "}
                <a href="https://creativecommons.org/licenses/by-nc-nd/3.0/" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">CC BY-NC-ND 3.0</a>.
                Evidence-based emergency medicine reviews.
              </p>
            </div>

            <div className="border border-gray-200 rounded-lg p-4">
              <h3 className="text-sm font-semibold">ALiEM (Academic Life in Emergency Medicine)</h3>
              <p className="text-xs text-gray-500 mt-1">
                Paucis Verbis (PV) Cards and MEdIC Series from <a href="https://aliem.com" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">aliem.com</a>, licensed under{" "}
                <a href="https://creativecommons.org/licenses/by-nc-nd/3.0/" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">CC BY-NC-ND 3.0</a>.
                Clinical reference cards and medical education case discussions.
              </p>
            </div>
          </div>
        </section>

        {/* RAG vs Training */}
        <section className="mb-10">
          <h2 className="text-xl font-semibold mb-3">Use of Content</h2>
          <p className="text-sm leading-relaxed text-gray-700 mb-3">
            EM Protocols uses Retrieval-Augmented Generation (RAG), not AI model training. Source content is stored in a search index and retrieved as verbatim excerpts with citations. Content is not ingested into model weights, is not modified, and can be removed from the index at any time upon request.
          </p>
          <p className="text-sm leading-relaxed text-gray-700">
            This tool is used for educational and clinical decision support purposes only and is not operated commercially.
          </p>
        </section>

        <div className="border-t border-gray-200 pt-6 text-xs text-gray-400">
          © {new Date().getFullYear()} EM Protocols. All rights reserved.
        </div>
      </div>
    </div>
  );
}
